hibernate.connection.url=jdbc:mysql://localhost:3307/sakila
hibernate.connection.username=root
hibernate.connection.password=hakim@123
#hibernate.hbm2ddl.auto=update

hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true